import { toast_error_option, toast_sucess_option } from "@/utils/toast"
import { Toaster } from "react-hot-toast"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {children}
      <Toaster
        position="top-right"
        reverseOrder={false}
        toastOptions={{
          success: { ...toast_sucess_option },
          error: { ...toast_error_option },
        }}
      />
    </>
  )
}
