import { IStory } from "@/types/home.types.";

export const stories_arr: IStory[] = [
    {
        id: 1,
        name: 'Dial',
        user_id: '623sdwa2522342sd8',
        story_image: '/story-2.png',
        caption: 'some caption',
    },
    {
        id: 2,
        name: 'Dial',
        user_id: '623sdwa2522342sd8',
        story_image: '/story-3.png',
        caption: 'some caption',
    },
    {
        id: 3,
        name: 'Dial',
        user_id: '623sdwa2522342sd8',
        story_image: '/story-4.png',
        caption: 'some caption',
    },
    {
        id: 4,
        name: 'Dial',
        user_id: '623sdwa2522342sd8',
        story_image: '/story-5.png',
        caption: 'some caption',
    },
    {
        id: 5,
        name: 'Dial',
        user_id: '623sdwa2522342sd8',
        story_image: '/story-2.png',
        caption: 'some caption',
    },
    {
        id: 6,
        name: 'Dial',
        user_id: '623sdwa2522342sd8',
        story_image: '/story-3.png',
        caption: 'some caption',
    },
    {
        id: 7,
        name: 'Dial',
        user_id: '623sdwa2522342sd8',
        story_image: '/story-4.png',
        caption: 'some caption',
    },
    {
        id: 8,
        name: 'Dial',
        user_id: '623sdwa2522342sd8',
        story_image: '/story-5.png',
        caption: 'some caption',
    },
    {
        id: 9,
        name: 'Dial',
        user_id: '623sdwa2522342sd8',
        story_image: '/story-2.png',
        caption: 'some caption',
    },
    {
        id: 10,
        name: 'Dial',
        user_id: '623sdwa2522342sd8',
        story_image: '/story-3.png',
        caption: 'some caption',
    },
    {
        id: 11,
        name: 'Dial',
        user_id: '623sdwa2522342sd8',
        story_image: '/story-4.png',
        caption: 'some caption',
    },
    {
        id: 12,
        name: 'Dial',
        user_id: '623sdwa2522342sd8',
        story_image: '/story-5.png',
        caption: 'some caption',
    },
]
