import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import "./globals.scss";

import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

const quickSand = Quicksand({
  weight: ['400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html>
        <body className={quickSand.className}>
          {children}
        </body>
      </html>
    </>
  )
}
